# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'font.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(287, 206)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Font_Box = QtWidgets.QFontComboBox(Form)
        self.Font_Box.setObjectName("Font_Box")
        self.gridLayout.addWidget(self.Font_Box, 0, 0, 1, 1)
        self.input_num = QtWidgets.QSpinBox(Form)
        self.input_num.setMinimum(2)
        self.input_num.setMaximum(72)
        self.input_num.setSingleStep(2)
        self.input_num.setProperty("value", 8)
        self.input_num.setObjectName("input_num")
        self.gridLayout.addWidget(self.input_num, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setAutoDefault(True)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 2, 0, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # ----------------------------------------
        self.setter_type_font()
        self.updater_example()

        self.Font_Box.currentFontChanged.connect(self.updater_example)
        self.input_num.valueChanged.connect(self.updater_example)

    def setter_type_font(self):
        try:
            with open("setting.json","r") as File:
                dict_font = json.loads(File.read())
                self.Font_Box.setCurrentText(dict_font["type_font"])
                self.input_num.setValue(dict_font["size_font"])
        except:
            pass

    
    def getter_font(self):
        size_font = self.input_num.value()
        family_font = self.Font_Box.currentText()           
        

        mydict = {"size_font":size_font,"type_font":family_font}

        return mydict

    def maker_font(self):
        size_font = self.getter_font()["size_font"]
        family_font = self.getter_font()["type_font"]
        self.font = QtGui.QFont()
        self.font.setPointSize(size_font)
        self.font.setFamily(family_font)

        return self.font

    def updater_example(self):


        self.label.setFont(self.maker_font())
        self.label_2.setFont(self.maker_font())
        self.label_3.setFont(self.maker_font())
        self.label_4.setFont(self.maker_font())







    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Font"))
        self.groupBox.setTitle(_translate("Form", "Exampke"))
        self.label.setText(_translate("Form", "A B C D E F G H"))
        self.label_2.setText(_translate("Form", "a b c d e f g h"))
        self.label_3.setText(_translate("Form", "1 2 3 4 5 6 7 8 9 0"))
        self.label_4.setText(_translate("Form", "= > < \" \' => <= ! == != <> >= { } @ $ #"))
        self.btn_save.setText(_translate("Form", "Save"))
        self.btn_cancel.setText(_translate("Form", "Cansel"))